spring:
  main:
    allow-circular-references: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/jupiter}
    username: ${SPRING_DATASOURCE_USERNAME:artem}
    password: ${SPRING_DATASOURCE_PASSWORD:admin-am}

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql

server:
  port: 9000

