spring:
  main:
    allow-circular-references: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/jupiter}
    username: ${SPRING_DATASOURCE_USERNAME:artem}
    password: ${SPRING_DATASOURCE_PASSWORD:admin-am}

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 642309214604-jqg753lnbgvdrcs9qfjfa8v0264pt3lj.apps.googleusercontent.com
            clientSecret: ${clientSecret}
            redirectUri: http://localhost:9000/auth2/authorization/google
            scope: openid, profile, email

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql

server:
  port: 9000

