spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jupiter
    username: artem
    password: artem
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql

security:
  oauth2:
    client:
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid profile email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 9000

